services:
  # External Services
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"   # Communication port
      - "15672:15672" # Dashboard
    networks:
      - ds-network

  # DATABASES
  user-db:
    image: postgres:15
    container_name: user_postgres_db
    environment:
      POSTGRES_USER: abdulla
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - ds-network

  booking_wallet_db:
    image: postgres:15
    container_name: booking_wallet_postgres
    environment:
      POSTGRES_USER: abdulla
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: booking_wallet_db
    ports:
      - "5433:5432"
    volumes:
      - booking_wallet_data:/var/lib/postgresql/data
    networks:
      - ds-network
  category_db: 
    image: postgres:15
    container_name: category_postgres
    environment:
      POSTGRES_USER: abdulla
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: category_db
    ports: ["5434:5432"]
    volumes:
      - category_db_data:/var/lib/postgresql/data
    networks: [ds-network]

  # Services
  user-service:
    build: ./User-Service
    container_name: user_service_api
    ports:
      - "5000:5000"
    volumes:
      - ./User-Service:/app
    depends_on:
      - user-db
    networks:
      - ds-network

  category-service:
    build: ./CategoryService
    container_name: category_app
    ports: ["8082:8080"]
    volumes:
      - ./CategoryService:/app
    depends_on: [category_db]
    networks: [ds-network]

  booking-wallet-service:
    build:
      context: ./BookingWalletService
      dockerfile: Dockerfile
    container_name: booking_wallet_ejb_service
    ports:
      - "8081:8080"
    depends_on:
      - booking_wallet_db
      - rabbitmq
    networks:
      - ds-network

  notification-service:
    build: ./NotificationService
    container_name: notification_app
    ports: ["8083:8080"]
    volumes:
      - ./NotificationService:/app
    depends_on: [rabbitmq]
    networks: [ds-network]

networks:
  ds-network:
    driver: bridge

volumes:
  user_db_data:
  booking_wallet_data:
  category_db_data: