spring.application.name=category-service
server.port=8080

spring.datasource.url=jdbc:postgresql://category_db:5432/category_db
spring.datasource.username=abdulla
spring.datasource.password=password123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
